### ISSUE TITLE
Expand Equipment

### ISSUE THREAD

**Issue by Mudpuppy12** [drl2/ezd6-fvtt#14]
Currently equipment can be Gear, Potion, Scroll, Weapon. 

It would be great if we can add trinkets, jewelry , magical armor and weapons, and unsual magic (misc) catagories?

**Comment by Mudpuppy12** [comment]
Or just a simple 'magic' category.

**Comment by drl2** [comment]
Had other requests for new categories with different breakdowns; to keep things simple, added "Magic" and "Other".
