### ISSUE TITLE
Foundry Version 10 minor compatibility issues

### ISSUE THREAD

**Issue by tbsvttr** [drl2/ezd6-fvtt#6]
Hi and thanks for your wonderful game system module! You are doing both the Foundry and the EZD6 community a huge service.

However, with Foundry 10, there are two minor incompatibilities with the current API:

```
[ezd6] The package "ezd6" contains "dependencies" which is deprecated in favor of "relationships.requires"
[ezd6] The package "ezd6" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object
```

It would be very nice if you could fix this.

**Comment by drl2** [comment]
v1.0.1 just released should fix these & maintain v9 compatibility.

Users who look at the browser's debug console will still see deprecation warnings while playing a world based on this system; fixes for these will happen in some later release because those fixes will break v9 compatibility.
